#!/bin/bash

function update() {
  wget https://tlauncher.org/jar -P /tmp
  unzip /tmp/jar -d /tmp/tlauncher
  sudo mv /tmp/tlauncher/*.jar /usr/share/tlauncher/tlauncher.jar
  rm /tmp/jar
  rm -rf /tmp/tlauncher/
}

function usage() {
  echo "
  Usage:
    --update -u | Update tlauncher.jar
    nothing     | Launch TLauncher
  "
}


while [[ "$1" ]]; do
  case "$1" in
    "--update" | "-u")
      update ; exit
      ;;
    *)
      usage ; exit
      ;;
  esac
  shift
done


java -jar /usr/share/tlauncher/tlauncher.jar